import { Menu } from "@/components/layout/menu";
import type { Metadata } from "next";
import { Roboto_Flex } from 'next/font/google';
import "./globals.css";

const roboto = Roboto_Flex({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased h-screen relative `}
      >
        {children}
        <Menu />
      </body>
    </html>
  );
}
